image: docker:stable
services:
- docker:dind
variables:
  KUBE_CONTEXT: dh-backend/dh-backend-user-sv:kube-agent
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  CS_DEFAULT_BRANCH_IMAGE: "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHA"
  ROLLOUT_RESOURCE_TYPE: deployment
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
workflow:
  rules:
  - if: $BUILDPACK_URL || $AUTO_DEVOPS_EXPLICITLY_ENABLED == "1" || $DOCKERFILE_PATH
  - exists:
    - Dockerfile
stages:
  - build-push-docker
  - deploy-staging


  
build-push-docker-image-job:
  stage: build-push-docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
  - |
    if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
      tag=""
      echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
    else
      tag=":$CI_COMMIT_REF_SLUG"
      echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
    fi
  - docker build --pull -t "$CS_DEFAULT_BRANCH_IMAGE" .
  - docker push "$CS_DEFAULT_BRANCH_IMAGE"


deploy:staging:
  image:
    name: bitnami/kubectl:latest
    entrypoint:
    - ''
  stage: deploy-staging
  variables:
    MANIFEST_PROJECT_ID: 30770380
    TARGET_ENVIRONMENT: development
    SERVICE: user-service
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl set image $ROLLOUT_RESOURCE_TYPE/$SERVICE $SERVICE=$CS_DEFAULT_BRANCH_IMAGE -n $TARGET_ENVIRONMENT
  environment:
    name: "$TARGET_ENVIRONMENT"


